### ISSUE TITLE
看到这个项目，感觉很不错

### ISSUE THREAD

**Issue by afyji** [toxmc/statistics#1]
github上说，是通过客户端udp上报的方式去发送数据，在example中也看到了。发送至55656端口
而在配置文件中，又看到是通过udp发送广播，然后tcp去拉取统计数据。

在管理页面，也发现了“无法从以下数据源获取数据:192.168.0.188::55858 ”
请问有相关的文档去对这个项目进行一些解释么

**Comment by afyji** [comment]
能否获得你的联系方式  我的QQ  157581768

**Comment by toxmc** [comment]
“无法从以下数据源获取数据:192.168.0.188::55858 ”这个是我传上去的代码里有缓存造成的，删除掉源码里面的缓存就好了，也可以在管理页面中去除。
你可以在swoole的各个群里看到我，哈哈。
