### ISSUE TITLE
样式加载不出来

### ISSUE THREAD

**Issue by ganxiangdong** [toxmc/statistics#2]
您好，样式加载不出来是什么情况哇？
Resource interpreted as Stylesheet but transferred with MIME type text/html: "http://192.168.88.2:55655/css/bootstrap.min.css".
192.168.88.2/:16 Resource interpreted as Stylesheet but transferred with MIME type text/html: "http://192.168.88.2:55655/css/style.css".
jquery.min.js:1 Uncaught SyntaxError: Unexpected token <
bootstrap.min.js:1 Uncaught SyntaxError: Unexpected token <
scripts.js:1 Uncaught SyntaxError: Unexpected token <
jquery.min.js:1 Uncaught SyntaxError: Unexpected token <
highcharts.js:1 Uncaught SyntaxError: Unexpected token <
?date=2015-10-25&:95 Uncaught ReferenceError: Highcharts is not defined

**Comment by ganxiangdong** [comment]
原来是没有配置nginx,还以为http_server处理了

**Comment by toxmc** [comment]
静态文件现在还是交给nginx处理，http_server处理静态文件优势不明显。
