### ISSUE TITLE
关于collectStatistics在多worker并发操作$this->statisticData时的疑问

### ISSUE THREAD

**Issue by tanboname** [toxmc/statistics#6]
protected function collectStatistics($module, $interface, $cost_time, $success, $ip, $code, $msg)
	{
		// 统计相关信息
		if (! isset($this->statisticData[$ip])) {
			$this->statisticData[$ip] = array();
		}
		if (! isset($this->statisticData[$ip][$module])) {
			$this->statisticData[$ip][$module] = array();
		}
		if (! isset($this->statisticData[$ip][$module][$interface])) {
			$this->statisticData[$ip][$module][$interface] = array(
				'code' => array(),
				'suc_cost_time' => 0,
				'fail_cost_time' => 0,
				'suc_count' => 0,
				'fail_count' => 0
			);
		}
		if (! isset($this->statisticData[$ip][$module][$interface]['code'][$code])) {
			$this->statisticData[$ip][$module][$interface]['code'][$code] = 0;
		}
		$this->statisticData[$ip][$module][$interface]['code'][$code] ++;
		if ($success) {
			$this->statisticData[$ip][$module][$interface]['suc_cost_time'] += $cost_time;
			$this->statisticData[$ip][$module][$interface]['suc_count'] ++;
		} else {
			$this->statisticData[$ip][$module][$interface]['fail_cost_time'] += $cost_time;
			$this->statisticData[$ip][$module][$interface]['fail_count'] ++;
		}
	}

请问并发时是如何保证$this->statisticData不会产生多个worker同时操作此变量的

**Comment by toxmc** [comment]
各个worker进程中的$this->statisticData是不会共享数据的

**Comment by bencen** [comment]
多并发的情况下你的定时器只写在$worker_id==0的时候才有。其他没有，这时候其他的statisticData的不会写进去。
