### ISSUE TITLE
没看明白server和web是靠什么打通数据的？

### ISSUE THREAD

**Issue by xinglu1983** [toxmc/statistics#7]
server端把数据收集到了statisticData里
web端从\Statistics\Lib\Cache::$statisticDataCache['statistic']里读数据，
问题是statisticData和\Statistics\Lib\Cache::$statisticDataCache['statistic']是在哪里打通数据的？

**Comment by toxmc** [comment]
web是通过tcp客户端去server端取数据的。
你从Web的index.php一步一步的跟。

**Comment by xinglu1983** [comment]
感谢回复。
我顺着index.php调试了一遍，还是有疑问。
在页面请求数据的时候，module和interface 都是在index.php里通过_GET接受的，然后一直传递，直到请求数据源的task方法，但是我第一次打开 url//?fn=statistic 监控标签页面的时候，并没有任何的module和interface变量传过来，这时候数据源的provide文件里的获取数据的方法getStatistic，检测到module为空就直接return了，是我哪里没有配置好吗？
按理说，我第一次打开监控页面，应该有个默认的module传过去吧，取一个module数据的列表，下次点击module和interface名称的时候，才会看具体的数据展示。

**Comment by toxmc** [comment]
第一次打开取得是总的数据
