### ISSUE TITLE
node客户端

### ISSUE THREAD

**Issue by prettyyjnic** [toxmc/statistics#8]
有没有node 写的客户端可以使用？

**Comment by toxmc** [comment]
暂时没有哦，我们这现在只提供给php使用的，如果你熟悉node的可以根据php的client改写下

**Comment by prettyyjnic** [comment]
不小心自己写出来了。。
```

function pack(moduleName, interfaceName, costTime, success, code, msg) {
    var params = {
        'module': moduleName,
        'interface': interfaceName,
        'cost_time': costTime,
        'success': success,
        'time': phpjs.time(),
        'code': code,
        'msg': msg
    };
    var str = JSON.stringify(params);
    var buf1 = Buffer.alloc(2000);
    buf1.writeInt32BE(Buffer.byteLength(str));
    var buf2 = Buffer.from(str);
    return Buffer.concat([buf1, buf2]);
}

var stats = function (interfaceName, costTime, success, code, msg) {
    var data = pack("Bigo_Activity", interfaceName, costTime, success, code, msg);
    client.send(data, 55857, '157.119.233.91');
}
```

**Comment by prettyyjnic** [comment]
function pack(moduleName, interfaceName, costTime, success, code, msg) {
    var params = {
        'module': moduleName,
        'interface': interfaceName,
        'cost_time': costTime,
        'success': success,
        'time': phpjs.time(),
        'code': code,
        'msg': msg
    };
    var str = JSON.stringify(params);
    var buf1 = Buffer.alloc(2000);
    buf1.writeInt32BE(Buffer.byteLength(str));
    var buf2 = Buffer.from(str);
    return Buffer.concat([buf1, buf2]);
}
const port = 1111;
const address = 127.0.0.1;
var stats = function (interfaceName, costTime, success, code, msg) {
    var data = pack("Bigo_Activity", interfaceName, costTime, success, code, msg);
    client.send(data, 1111, '127.0.0.1');
}

**Comment by prettyyjnic** [comment]
不小心写出来了，简单粗暴的版本
const port = 1111;
const host = 127.0.0.1;

function pack(moduleName, interfaceName, costTime, success, code, msg) {
    var params = {
        'module': moduleName,
        'interface': interfaceName,
        'cost_time': costTime,
        'success': success,
        'time': parseInt(Date.now() /1000),
        'code': code,
        'msg': msg
    };
    var str = JSON.stringify(params);
    var buf1 = Buffer.alloc(2000);
    buf1.writeInt32BE(Buffer.byteLength(str));
    var buf2 = Buffer.from(str);
    return Buffer.concat([buf1, buf2]);
}

var stats = function (moduleName, interfaceName, costTime, success, code, msg) {
    var data = pack(moduleName, interfaceName, costTime, success, code, msg);
    client.send(data, port, host);
}

**Comment by toxmc** [comment]
赞👍
